---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Debug nilai Standby pada env .IDFGISU1"
      debug:
        msg: "Standby DB is set to: {{ standby_db_IDFGISU1 }}"
        
##############################
- name: CR SU1
  hosts: "{{ standby_db_IDFGISU1 }}"
  gather_facts: no
  tasks:      
    - name: Check_Replication_Primary_to_Standby
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin        
        sqlplus -s / as sysdba
        alter system archive log current;
        alter system archive log current;
        alter system archive log current;
      register: db_open

    - name: Check for success in database status
      fail:
        msg: "System could not be altered. Output: {{ db_open.stdout }}"
      when: "'System altered' not in db_open.stdout"

    - name: Display success message
      debug:
        msg: "System successfully altered.\n{{ db_open.stdout }}"
      when: "'System altered' in db_open.stdout"


