---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Debug nilai Standby pada env .IDFGISU1"
      debug:
        msg: "Standby DB is set to: {{ standby_db_IDFGISU1 }}"
        
##############################
- name: CR SU1
  hosts: "{{ standby_db_IDFGISU1 }}"
  gather_facts: no
  tasks:      
    - name: Check_Replication_Primary_to_Standby
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        for i in {1..3}; do
          echo "ALTER SYSTEM ARCHIVE LOG CURRENT;" | sqlplus -s / as sysdba
        done
      register: db_switchlog
      ignore_errors: yes

    - name: Check SQL command output
      fail:
        msg: "SQL command did not execute successfully. Output: {{ db_switchlog.stdout }}"
      when: "'System altered' not in db_switchlog.stdout"

    - name: Display SQL command result
      debug:
        msg: "{{ db_switchlog.stdout_lines }}"


