---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Debug nilai STANDBY pada env .IDFGISU1"
      debug:
        msg: "STANDBY DB is set to: {{ standby_db_IDFGISU1 }}"
        
##############################
- hosts: "{{ standby_db_IDFGISU1 }}"
  gather_facts: no
  tasks:
    - name: Jalankan query perbandingan log archive dan log history
      shell: |
        . .IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin        
        sqlplus -s / as sysdba <<EOF
        SET LINESIZE 200
        SET PAGESIZE 100
        SET FEEDBACK OFF
        SET HEADING ON
        SELECT ARCH.THREAD# "Thread",
               ARCH.SEQUENCE# "Last Sequence Received",
               APPL.SEQUENCE# "Last Sequence Applied",
               (ARCH.SEQUENCE# - APPL.SEQUENCE#) "Difference"
        FROM
          (SELECT THREAD# ,SEQUENCE#
           FROM V$ARCHIVED_LOG
           WHERE (THREAD#,FIRST_TIME ) IN
             (SELECT THREAD#,MAX(FIRST_TIME)
              FROM V$ARCHIVED_LOG
              GROUP BY THREAD#)) ARCH,
          (SELECT THREAD# ,SEQUENCE#
           FROM V$LOG_HISTORY
           WHERE (THREAD#,FIRST_TIME ) IN
             (SELECT THREAD#,MAX(FIRST_TIME)
              FROM V$LOG_HISTORY
              GROUP BY THREAD#)) APPL
        WHERE ARCH.THREAD# = APPL.THREAD#;
        exit;
        EOF
      register: log_comparison_result

    - name: Tampilkan hasil query perbandingan log
      debug:
        var: log_comparison_result.stdout
