---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari PRIMARY"
      debug:
        msg: "{{ primary_db_IDFGICU1 }}"

    - name: "Debug nilai DEV pada env .IDFGICU1"
      debug:
        msg: "Primary DB is set to: {{ primary_db_IDFGICU1 }}"
        
###############################
- name: DEFER CU1
  hosts: "{{ primary_db_IDFGICU1 }}"
  gather_facts: no
  tasks:
    - name: Set DEFER log_archive_dest_state_2 - PRIMARY CU1
      shell: |
        . ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "ALTER SYSTEM SET log_archive_dest_state_2=DEFER SCOPE=BOTH;" | sqlplus -s / as sysdba
      register: defer_cu1_primary
      ignore_errors: yes

    - name: Validasi DEFER - PRIMARY CU1
      fail:
        msg: "Gagal DEFER di PRIMARY CU1: {{ defer_cu1_primary.stdout }}"
      when: "'System altered' not in defer_cu1_primary.stdout"
