---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari PRIMARY"
      debug:
        msg: "{{ primary_db_IDFGISU1 }}"

    - name: "Debug nilai DEV pada env .IDFGISU1"
      debug:
        msg: "Primary DB is set to: {{ primary_db_IDFGISU1 }}"
        
###############################
- hosts: "{{ primary_db_IDFGISU1 }}"
  gather_facts: no
  tasks:
    - name: Set DEFER log_archive_dest_state_2 - PRIMARY SU1
      shell: |
        . ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "alter system set log_archive_dest_state_2=DEFER scope=both;" | sqlplus -s / as sysdba
      register: defer_su1_primary
      ignore_errors: yes

    - name: Validasi DEFER - PRIMARY SU1
      fail:
        msg: "Gagal DEFER di PRIMARY SU1: {{ defer_su1_primary.stdout }}"
      when: "'System altered' not in defer_su1_primary.stdout"
