---
- name: Cek ROLE database untuk env profile .IDFGICU1
  hosts: 192.168.1.211
  gather_facts: no
  tasks:
    - name: Cek role di ENV .IDFGICU1
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo 'SET HEADING OFF
        SET FEEDBACK OFF
        SELECT database_role FROM v$database; 
        EXIT;' | sqlplus -s / as sysdba
      register: db1_role_idfgicu1
      ignore_errors: yes

    - name: Display the output
      debug: msg="{{ db1_role_idfgicu1.stdout }}"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGICU1: ""

    - name: Display database role for DEV
      debug:
        msg: "DEV"
      register: dev
      when: "'PRIMARY' in db1_role_idfgicu1.stdout"

    - name: Display database role for UAT
      debug:
        msg: "DEV"
      register: uat
      when: "'PHYSICAL STANDBY' in db1_role_idfgicu1.stdout"

    - name: Set DEV
      set_stats:
        data:
          DEV_IDFGICU1: "192.168.1.211"
      when: "'PRIMARY' in db1_role_idfgicu1.stdout"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGICU1: "192.168.1.211"
      when: "'PHYSICAL STANDBY' in db1_role_idfgicu1.stdout"

###########

- name: Cek ROLE database untuk env profile .IDFGICU1
  hosts: 192.168.1.222
  gather_facts: no
  tasks:
    - name: Cek role di ENV .IDFGICU1
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo 'SET HEADING OFF
        SET FEEDBACK OFF
        SELECT database_role FROM v$database; 
        EXIT;' | sqlplus -s / as sysdba
      register: db2_role_idfgicu1
      ignore_errors: yes

    - name: Display the output
      debug: msg="{{ db2_role_idfgicu1.stdout }}"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGICU1: ""

    - name: Display database role for DEV
      debug:
        msg: "DEV"
      register: dev
      when: "'PRIMARY' in db2_role_idfgicu1.stdout"

    - name: Display database role for UAT
      debug:
        msg: "DEV"
      register: uat
      when: "'PHYSICAL STANDBY' in db2_role_idfgicu1.stdout"

    - name: Set DEV
      set_stats:
        data:
          DEV_IDFGICU1: "192.168.1.222"
      when: "'PRIMARY' in db2_role_idfgicu1.stdout"

    - name: Set db standby
      set_stats:
        data:
          UAT_IDFGICU1: "192.168.1.222"
      when: "'PHYSICAL STANDBY' in db2_role_idfgicu1.stdout"

###########
- name: Cek ROLE database untuk env profile .IDFGISU1
  hosts: 192.168.1.211
  gather_facts: no
  tasks:
    - name: Cek role di ENV .IDFGISU1
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo 'SET HEADING OFF
        SET FEEDBACK OFF
        SELECT database_role FROM v$database; 
        EXIT;' | sqlplus -s / as sysdba
      register: db1_role_idfgisu1
      ignore_errors: yes

    - name: Display the output
      debug: msg="{{ db1_role_idfgisu1.stdout }}"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGISU1: ""

    - name: Display database role for DEV
      debug:
        msg: "DEV"
      register: dev
      when: "'PRIMARY' in db1_role_idfgisu1.stdout"

    - name: Display database role for UAT
      debug:
        msg: "DEV"
      register: uat
      when: "'PHYSICAL STANDBY' in db1_role_idfgisu1.stdout"

    - name: Set DEV
      set_stats:
        data:
          DEV_IDFGISU1: "192.168.1.211"
      when: "'PRIMARY' in db1_role_idfgisu1.stdout"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGISU1: "192.168.1.211"
      when: "'PHYSICAL STANDBY' in db1_role_idfgisu1.stdout"

###########
- name: Cek ROLE database untuk env profile .IDFGISU1
  hosts: 192.168.1.222
  gather_facts: no
  tasks:
    - name: Cek role di ENV .IDFGISU1
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo 'SET HEADING OFF
        SET FEEDBACK OFF
        SELECT database_role FROM v$database; 
        EXIT;' | sqlplus -s / as sysdba
      register: db2_role_idfgisu1
      ignore_errors: yes

    - name: Display the output
      debug: msg="{{ db2_role_idfgisu1.stdout }}"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGISU1: ""

    - name: Display database role for DEV
      debug:
        msg: "DEV"
      register: dev
      when: "'PRIMARY' in db2_role_idfgisu1.stdout"

    - name: Display database role for UAT
      debug:
        msg: "DEV"
      register: uat
      when: "'PHYSICAL STANDBY' in db2_role_idfgisu1.stdout"

    - name: Set DEV
      set_stats:
        data:
          DEV_IDFGISU1: "192.168.1.222"
      when: "'PRIMARY' in db2_role_idfgisu1.stdout"

    - name: Set UAT
      set_stats:
        data:
          UAT_IDFGISU1: "192.168.1.222"
      when: "'PHYSICAL STANDBY' in db2_role_idfgisu1.stdout"
