---
- name: Cek env .IDFGISU1
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari DEV"
      debug:
        msg: "{{ primary_db_IDFGISU1 }}"
        
    - name: "Tampilkan data dari UAT"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Cek apakah PRIMARY ada di DEV"
      assert:
        that:
          - primary_db_IDFGISU1 == '192.168.1.211'
        fail_msg: "Pengecekan gagal: DEV tidak PRIMARY"
        success_msg: "Pengecekan berhasil: DEV adalah PRIMARY"

    - name: "Cek apakah STANDBY ada di UAT"
      assert:
        that:
          - standby_db_IDFGISU1 == '192.168.1.222'
        fail_msg: "Pengecekan gagal: UAT tidak STANDBY"
        success_msg: "Pengecekan berhasil: UAT adalah STANDBY"
