---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Debug nilai STANDBY pada env .IDFGISU1"
      debug:
        msg: "STANDBY DB is set to: {{ standby_db_IDFGISU1 }}"

########################
- name: OPEN DB SU1
  hosts: "{{ standby_db_IDFGISU1 }}"
  gather_facts: no
  tasks:
    - name: Jalankan perintah ALTER DATABASE OPEN
      shell: |
        . ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "ALTER DATABASE OPEN;" | sqlplus -s / as sysdba
      register: db_open
      ignore_errors: yes

    - name: Check for success in database status
      fail:
        msg: "Database could not be opened. Output: {{ db_open.stdout }}"
      when: "'Database altered' not in db_open.stdout"

    - name: Display success message
      debug:
        msg: "Database successfully opened.\n{{ db_open.stdout }}"
      when: "'Database altered' in db_open.stdout"
