---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGISU1 }}"

    - name: "Debug nilai STANDBY pada env .IDFGISU1"
      debug:
        msg: "STANDBY DB is set to: {{ standby_db_IDFGISU1 }}"

########################
- name: OPEN DB SU1
  hosts: "{{ standby_db_IDFGISU1 }}"
  tasks:
    - name: Jalankan perintah ALTER DATABASE OPEN
      shell: |
        . ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin        
        sqlplus -S / as sysdba <<EOF
        SET FEEDBACK OFF
        SET HEAD OFF
        ALTER DATABASE OPEN;
        EXIT
        EOF
      register: hasil_open_db
      
    - name: Tampilkan hasil open database
      debug:
        var: hasil_open_db.stdout

    - name: Validasi hasil OPEN berhasil
      fail:
        msg: "⛔ ALTER DATABASE OPEN gagal dilakukan"
      when: "'Database altered' not in hasil_open_db.stdout"
