---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari UAT"
      debug:
        msg: "{{ UAT_IDFGICU1 }}"

    - name: "Tampilkan data dari DEV"
      debug:
        msg: "{{ DEV_IDFGICU1 }}"

    - name: "Debug nilai DEV pada env .IDFGICU1"
      debug:
        msg: "Primary DB is set to: {{ DEV_IDFGICU1 }}"

    - name: "Debug nilai UAT pada env .IDFGICU1"
      debug:
        msg: "Standby DB is set to: {{ UAT_IDFGICU1 }}"

#################
- hosts: 
    - "{{ DEV_IDFGICU1 }}"
    - "{{ UAT_IDFGICU1 }}"
  gather_facts: no
  tasks:
    - name: Swing DB di ENV .IDFGICU1 (dummy)
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo 'SELECT inst_id, name, value FROM gv$dataguard_stats;
        EXIT;' | sqlplus -s / as sysdba
      register: db1_role
      ignore_errors: true

    - name: Display the output
      debug: msg="{{ db1_role.stdout }}"
