---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_IDFGICU1 }}"

    - name: "Debug nilai STANDBY pada env .IDFGICU1"
      debug:
        msg: "STANDBY DB is set to: {{ standby_db_IDFGICU1 }}"
        
##############################
- name: STARTSEND CU1
  hosts: "{{ standby_db_IDFGICU1 }}"
  gather_facts: no
  tasks:
    - name: Set ENABLE log_archive_dest_state_2
      shell: |
        . ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "ALTER SYSTEM SET log_archive_dest_state_2=ENABLE SCOPE=BOTH;" | sqlplus -s / as sysdba
      register: enable_cu1
      ignore_errors: yes

    - name: Validasi ENABLE
      fail:
        msg: "Gagal ENABLE di CU1: {{ enable_cu1.stdout }}"
      when: "'System altered' not in enable_cu1.stdout"
