---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tampilkan data dari PRIMARY"
      debug:
        msg: "{{ primary_db_IDFGISU1 }}"

    - name: "Debug nilai DEV pada env .IDFGISU1"
      debug:
        msg: "Primary DB is set to: {{ primary_db_IDFGISU1 }}"
        
##############################
- hosts:
    - "{{ primary_db_IDFGISU1 }}"
  tasks:
    - name: Cek status switchover dari database
      shell: |
        . ~/.IDFGISU1
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        sqlplus -S / as sysdba <<EOF
        SET HEAD OFF
        SET FEEDBACK OFF
        SET PAGESIZE 0
        SELECT database_role || '|' || switchover_status FROM v\$database;
        EXIT
        EOF
      register: db_role_status
      ignore_errors: yes

    - name: Display raw database role status
      debug:
        msg: "Database role status raw output: {{ db_role_status.stdout }}"

    - name: Extract role and switchover status
      set_fact:
        db_role: "{{ db_role_status.stdout.split('|')[0] | trim }}"
        switchover_status: "{{ db_role_status.stdout.split('|')[1] | trim }}"

    - name: Debug extracted values
      debug:
        msg:
          - "Extracted role: {{ db_role }}"
          - "Switchover status: {{ switchover_status }}"

    - name: Check switchover status is TO STANDBY
      debug:
        msg: "Database switchover status is 'TO STANDBY'. Process can continue."
      when: switchover_status == "TO STANDBY"

    - name: Fail if switchover status is not TO STANDBY
      fail:
        msg: "Switchover status is not 'TO STANDBY'. Current status: {{ switchover_status }}"
      when: switchover_status != "TO STANDBY"

    - name: Commit switchover jika status TO STANDBY
      shell: |
        . ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        sqlplus -S / as sysdba <<EOF
        ALTER DATABASE COMMIT TO SWITCHOVER TO STANDBY WITH SESSION SHUTDOWN;
        EXIT
        EOF
      register: alter
      ignore_errors: yes

    - name: Check for success in database status
      fail:
        msg: "Database could not be opened. Output: {{ alter.stdout }}"
      when: "'Database altered' not in alter.stdout"
