---
- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:

    - name: 🔁 Loop pengecekan semua WordPress
      vars:
        summary: ""
      block:
        - name: 🔍 Cek koneksi ke {{ item.name }}
          uri:
            url: "{{ item.url }}"
            return_content: yes
            timeout: 10
          register: result
          failed_when: false
          loop: "{{ wordpress_sites }}"
          loop_control:
            label: "{{ item.name }}"
          delegate_to: localhost
          run_once: false

        - name: 🧠 Proses hasil & simpan summary
          set_fact:
            wp_summary: "{{ wp_summary | default([]) + [ _summary_line ] }}"
          vars:
            _summary_line: >-
              🌐 {{ item.name }} ({{ item.url }}):
              {% if 'Error establishing a database connection' in result.content %}
              ❌ Error koneksi database.
              {% elif 'setup-config.php' in result.content or 'Setup Configuration File' in result.content %}
              ⚠️ WordPress belum dikonfigurasi.
              {% elif 'WordPress' in result.content and result.status == 200 %}
              ✅ WordPress aktif (status {{ result.status }})
              {% else %}
              ❓ Tidak dikenali / kemungkinan tidak aktif.
              {% endif %}
          loop: "{{ wordpress_sites }}"
          loop_control:
            label: "{{ item.name }}"
          delegate_to: localhost
          run_once: false

    - name: 📨 Simpan summary ke notifikasi Ansible
      set_stats:
        data:
          wp_summary: |
            {{ wp_summary | join('\n') }}

    - name: 🔍 Tampilkan summary di log
      debug:
        var: wp_summary | join('\n')
