---
- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:
    - name: Siapkan list untuk summary hasil
      set_fact:
        wp_summary: []

    - name: Loop pengecekan WordPress
      block:
        - name: 🔍 Cek koneksi ke {{ item.name }}
          uri:
            url: "{{ item.url }}"
            return_content: yes
            timeout: 10
          register: result
          failed_when: false

        - name: 🔎 Analisis hasil dan simpan ke summary
          set_fact:
            wp_summary: "{{ wp_summary + [summary_line] }}"
          vars:
            summary_line: >-
              🌐 {{ item.name }} ({{ item.url }}):
              {% if 'Error establishing a database connection' in result.content %}
              ❌ Error koneksi database.
              {% elif 'setup-config.php' in result.content or 'Setup Configuration File' in result.content %}
              ⚠️ Belum dikonfigurasi.
              {% elif 'WordPress' in result.content and result.status == 200 %}
              ✅ WordPress aktif (status {{ result.status }})
              {% else %}
              ❓ Tidak dikenali atau tidak aktif.
              {% endif %}
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Simpan ringkasan ke notifikasi Ansible Tower
      set_stats:
        data:
          wp_summary: "{{ wp_summary | join('\n') }}"

    - name: Tampilkan ringkasan hasil di log
      debug:
        msg: "{{ wp_summary | join('\n') }}"
