---
- name: Cek kesehatan semua website WordPress dan kirim notifikasi email
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:

    - name: Inisialisasi list summary hasil cek
      set_fact:
        wp_summary: []

    - name: Loop per website WordPress
      block:

        - name: 🔍 Cek koneksi ke {{ item.name }}
          uri:
            url: "{{ item.url }}"
            return_content: yes
            timeout: 10
          register: result
          failed_when: false
          loop: "{{ wordpress_sites }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Buat ringkasan hasil cek untuk {{ item.name }}
          set_fact:
            wp_summary: "{{ wp_summary + [ summary_line ] }}"
          vars:
            summary_line: >-
              🌐 {{ item.name }} ({{ item.url }}):
              {% if 'Error establishing a database connection' in result.content %}
              ❌ Error koneksi database.
              {% elif 'setup-config.php' in result.content or 'Setup Configuration File' in result.content %}
              ⚠️ WordPress belum dikonfigurasi.
              {% elif 'WordPress' in result.content and result.status == 200 %}
              ✅ WordPress aktif (status {{ result.status }})
              {% else %}
              ❓ Status tidak dikenali atau situs tidak aktif.
              {% endif %}
          loop: "{{ wordpress_sites }}"
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: ❌ Tidak bisa konek ke {{ item.name }}
          set_fact:
            wp_summary: "{{ wp_summary + [ '❌ ' + item.name + ': Tidak dapat mengakses ' + item.url + ' (kemungkinan DNS/IP down)' ] }}"
          loop: "{{ wordpress_sites }}"
          loop_control:
            label: "{{ item.name }}"

    - name: Tampilkan ringkasan hasil cek WordPress
      debug:
        msg: "{{ wp_summary | join('\n') }}"

    - name: Kirim notifikasi email hasil cek WordPress
      mail:
        host: smtp.gmail.com
        port: 587
        username: 'yunusimsal@gmail.com'
        password: 'kuahjxvtbyvkqsep'
        to: 'yunusimsal@gmail.com'
        subject: "Laporan Cek Kesehatan WordPress"
        body: |
          Berikut adalah hasil pengecekan kesehatan website WordPress:

          {{ wp_summary | join('\n') }}

          Terima kasih.
        secure: starttls
