---
- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:
    - name: 🔍 Cek koneksi ke setiap website WordPress
      uri:
        url: "{{ item.url }}"
        return_content: no
        timeout: 10
        status_code: 200,301,302,403,404,500,502,503  # status yang diharapkan selain 200 juga diterima
      register: result
      failed_when: false
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"

    - name: 🌐 Tampilkan status code dan pesan sesuai hasil pengecekan
      vars:
        site: "{{ wordpress_sites[ansible_loop.index0] }}"
        res: "{{ result.results[ansible_loop.index0] }}"
      debug:
        msg: |
          Site: {{ site.name }}
          URL: {{ site.url }}
          Status HTTP: {{ res.status }}

          {% if res.status == 200 %}
          ✅ Website aktif dan berjalan normal.
          {% elif res.status in [301, 302] %}
          🔄 Website melakukan redirect.
          {% elif res.status == 403 %}
          ⛔ Akses ditolak (Forbidden).
          {% elif res.status == 404 %}
          ❌ Halaman tidak ditemukan (Not Found).
          {% elif res.status >= 500 %}
          ⚠️ Terjadi kesalahan server (Server Error).
          {% else %}
          ⚠️ Status HTTP tidak biasa: {{ res.status }}.
          {% endif %}
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
