---
- name: Test WordPress URL
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test akses WordPress
      uri:
        url: http://192.168.56.104:30149
        return_content: yes
        status_code: 200
      register: result

    - name: Tampilkan hasil
      debug:
        var: result.status

    - name: Periksa isi halaman
      debug:
        msg: "Berhasil akses WordPress!"
      when: "'WordPress' in result.content"
