- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:

    - name: 🔍 Cek koneksi ke WordPress sites
      uri:
        url: "{{ item.url }}"
        return_content: yes
        timeout: 10
      register: result
      failed_when: false
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"

    - name: 🌐 Tampilkan status HTTP setiap WordPress site
      debug:
        msg: "Status code {{ item_result.status }} untuk {{ item.url }}"
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        item_result: "{{ result.results[loop.index0] }}"

    - name: ❗ Deteksi error koneksi database
      debug:
        msg: "❗ [{{ item.name }}] Error: Tidak bisa konek ke database!"
      when: "'Error establishing a database connection' in item_result.content"
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        item_result: "{{ result.results[loop.index0] }}"

    - name: ⚠️ Deteksi halaman setup WordPress
      debug:
        msg: "⚠️ [{{ item.name }}] WordPress belum dikonfigurasi (setup-config.php)"
      when: "'setup-config.php' in item_result.content or 'Setup Configuration File' in item_result.content"
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        item_result: "{{ result.results[loop.index0] }}"

    - name: ✅ Halaman WordPress tampil normal
      debug:
        msg: "✅ [{{ item.name }}] WordPress aktif & halaman tampil normal!"
      when: "'WordPress' in item_result.content and item_result.status == 200"
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        item_result: "{{ result.results[loop.index0] }}"

    - name: 📝 Preview isi halaman
      debug:
        msg: |
          📝 [{{ item.name }}] Cuplikan konten:
          {{ item_result.content | regex_replace('\\s+', ' ') | truncate(250, True) }}
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        item_result: "{{ result.results[loop.index0] }}"
