---
- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:
    - name: 🔍 Cek koneksi ke setiap website WordPress
      uri:
        url: "{{ item.url }}"
        return_content: no
        timeout: 10
        status_code: 200,301,302,403,404,500,502,503
      register: result
      failed_when: false
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"

    - name: 🌐 Tampilkan status code dan pesan sesuai hasil pengecekan
      debug:
        msg: |
          Site: {{ wordpress_sites[item_index].name }}
          URL: {{ wordpress_sites[item_index].url }}
          Status HTTP: {{ result.results[item_index].status }}

          {% set status_code = result.results[item_index].status %}
          {% if status_code == 200 %}
          ✅ Website aktif dan berjalan normal.
          {% elif status_code in [301, 302] %}
          🔄 Website melakukan redirect.
          {% elif status_code == 403 %}
          ⛔ Akses ditolak (Forbidden).
          {% elif status_code == 404 %}
          ❌ Halaman tidak ditemukan (Not Found).
          {% elif status_code >= 500 %}
          ⚠️ Terjadi kesalahan server (Server Error).
          {% else %}
          ⚠️ Status HTTP tidak biasa: {{ status_code }}.
          {% endif %}
      loop: "{{ range(0, wordpress_sites|length) | list }}"
      loop_control:
        label: "{{ wordpress_sites[item_index].name }}"
      vars:
        item_index: "{{ item }}"
