- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wordpress_sites:
      - name: WordPress Test
        url: http://192.168.56.104:30149

  tasks:

    - name: 🔍 Cek koneksi ke WordPress sites
      uri:
        url: "{{ item.url }}"
        return_content: yes
        timeout: 10
      register: result
      failed_when: false
      loop: "{{ wordpress_sites }}"
      loop_control:
        label: "{{ item.name }}"

    - name: 🌐 Tampilkan status HTTP setiap WordPress site
      debug:
        msg: "Status code {{ item.1.status }} untuk {{ item.0.url }}"
      with_indexed_items: "{{ wordpress_sites }}"

    - name: ❗ Deteksi error koneksi database
      debug:
        msg: "❗ [{{ item.0.name }}] Error: Tidak bisa konek ke database!"
      when: "'Error establishing a database connection' in item.1.content"
      with_indexed_items: "{{ wordpress_sites }}"

    - name: ⚠️ Deteksi halaman setup WordPress
      debug:
        msg: "⚠️ [{{ item.0.name }}] WordPress belum dikonfigurasi (setup-config.php)"
      when: "'setup-config.php' in item.1.content or 'Setup Configuration File' in item.1.content"
      with_indexed_items: "{{ wordpress_sites }}"

    - name: ✅ Halaman WordPress tampil normal
      debug:
        msg: "✅ [{{ item.0.name }}] WordPress aktif & halaman tampil normal!"
      when: "'WordPress' in item.1.content and item.1.status == 200"
      with_indexed_items: "{{ wordpress_sites }}"

    - name: 📝 Preview isi halaman
      debug:
        msg: |
          📝 [{{ item.0.name }}] Cuplikan konten:
          {{ item.1.content | regex_replace('\\s+', ' ') | truncate(250, True) }}
      with_indexed_items: "{{ wordpress_sites }}"
