---
- name: Cek kesehatan semua website WordPress
  hosts: localhost
  gather_facts: false

  vars:
    wp_url: http://192.168.56.104:30149

  tasks:

    - name: 🔍 Cek koneksi ke WordPress
      uri:
        url: "{{ wp_url }}"
        return_content: yes
        timeout: 10
      register: result
      failed_when: false

    - name: ❗ Cek error DB
      set_fact:
        db_error: true
      when: "'Error establishing a database connection' in result.content"

    - name: ✅ Buat summary email
      set_fact:
        email_message: |
          Hasil Cek Website WordPress:
          
          URL: {{ wp_url }}
          Status: {{ result.status }}
          Waktu Respons: {{ result.elapsed }} detik
          
          {% if db_error is defined and db_error %}
          ⚠️ Terjadi error koneksi database!
          {% elif 'WordPress' in result.content %}
          ✅ WordPress tampil normal.
          {% else %}
          ❓ Halaman tidak dikenali atau kosong.
          {% endif %}

    - name: 📤 Kirim hasil cek ke email
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: yunusimsal@gmail.com
        password: "{{ lookup('env', 'GMAIL_APP_PASS') }}"
        to: yunusimsal@gmail.com
        subject: "🔔 Hasil Cek WordPress {{ ansible_date_time.iso8601 }}"
        body: "{{ email_message }}"
        subtype: plain
        secure: starttls
