---
- name: Test connectivity to Windows host
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows
  tasks:
    - name: Ping the Windows host
      win_ping:
      
    - name: Disable realtime monitoring
      win_powershell:
        script: Set-MpPreference -DisableRealtimeMonitoring $true
